Added my card in index.html
Bauddhik-Geeks/Resource-Card pull request #84
Opened 2022-10-13 15:28 UTC by sachin1293

Hi, @Nitesh-thapliyal , kindly merge this PR

2022-10-14 14:32 UTC, Nitesh-thapliyal requested changes

2022-10-14 14:32 UTC, Nitesh-thapliyal commented on index.html
> +                            <a href="https://www.youtube.com/playlist?list=PLjVLYmrlmjGdDps6HAwOOVoAtBPAgIOXL" target="_blank"
There is a typo can you fix it

2022-10-14 17:42 UTC, sachin1293 commented
Hi @Nitesh-thapliyal I fixed the typo.

2022-10-16 02:45 UTC, Nitesh-thapliyal approved these changes

2022-10-16 02:46 UTC, merged